version: '3.8'

services:
  backend:
    build: ./backend
    container_name: bursatil-backend
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build: ./frontend
    container_name: bursatil-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080/api/news
    depends_on:
      - backend
    restart: always
