services:
  backend:
    build: ./backend
    container_name: bursatil-backend
    ports:
      - "8081:8080"
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=http://backend:8080/api/news
    container_name: bursatil-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
